# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chester}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-05-06}
  s.default_executable = %q{chester}
  s.description = %q{This project use coffeescript and MVC to create an awesome framework for the Titanium system!}
  s.email = %q{tom@jackhq.com}
  s.executables = ["chester"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "bin/chester",
     "lib/chester.rb",
     "lib/chester/command.rb",
     "lib/chester/commands/base.rb",
     "lib/chester/commands/brew.rb",
     "lib/chester/commands/generate.rb",
     "lib/chester/commands/install.rb",
     "lib/chester/helpers.rb",
     "lib/chester/templates/chester.coffee",
     "lib/chester/templates/controller.coffee.erb",
     "lib/chester/templates/model.coffee.erb",
     "lib/chester/templates/view.coffee.erb",
     "readme.md",
     "spec/chester_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "views/patient/index.coffee",
     "views/patient/new.coffee"
  ]
  s.homepage = %q{http://github.com/twilson63/chester}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{MVC for Titanium Developer}
  s.test_files = [
    "spec/chester_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.6.5"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<erubis>, [">= 2.6.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<erubis>, [">= 2.6.5"])
  end
end

